<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AnggotaController;
use Illuminate\Support\Facades\Route;

// Authentication Routes (Generated by Laravel Auth, but ensuring they exist if using Breeze/UI)
// Assuming standard auth routes are loaded by default or require 'require __DIR__.'/auth.php';'
// Since I don't see auth.php require here, I'll assume standard Laravel 11 structure loads them elsewhere or I should wrap these.
// To be safe and fix the error, I will wrap the app routes in auth middleware.

// Public Routes
Route::get('login', [\App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('login');
Route::post('login', [\App\Http\Controllers\AuthController::class, 'login']);
Route::get('register', [\App\Http\Controllers\AuthController::class, 'showRegistrationForm'])->name('register');
Route::post('register', [\App\Http\Controllers\AuthController::class, 'register']);
Route::post('logout', [\App\Http\Controllers\AuthController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    
    // Anggota Routes
    Route::resource('anggota', AnggotaController::class); // Updated resource name and controller
    Route::post('anggota/{anggota}/create-user', [AnggotaController::class, 'createUser'])->name('anggota.create_user'); // Updated route and controller
    
    Route::resource('savings', \App\Http\Controllers\SavingController::class);
    Route::put('savings/{saving}/approve', [\App\Http\Controllers\SavingController::class, 'approve'])->name('savings.approve');
    Route::put('savings/{saving}/reject', [\App\Http\Controllers\SavingController::class, 'reject'])->name('savings.reject');
    
    Route::post('loans/settings/interest', [\App\Http\Controllers\LoanController::class, 'updateInterestRate'])->name('loans.settings.interest');
    Route::resource('loans', \App\Http\Controllers\LoanController::class);
    Route::put('loans/{loan}/approve', [\App\Http\Controllers\LoanController::class, 'approve'])->name('loans.approve');
    Route::put('loans/{loan}/reject', [\App\Http\Controllers\LoanController::class, 'reject'])->name('loans.reject');
    
    Route::resource('installments', \App\Http\Controllers\InstallmentController::class);
    Route::put('installments/{installment}/approve', [\App\Http\Controllers\InstallmentController::class, 'approve'])->name('installments.approve');
    Route::put('installments/{installment}/reject', [\App\Http\Controllers\InstallmentController::class, 'reject'])->name('installments.reject');
    
    Route::prefix('reports')->name('reports.')->group(function () {
        Route::get('/', [\App\Http\Controllers\ReportController::class, 'index'])->name('index');
        Route::get('/members', [\App\Http\Controllers\ReportController::class, 'members'])->name('members');
        Route::get('/savings', [\App\Http\Controllers\ReportController::class, 'savings'])->name('savings');
        Route::get('/loans', [\App\Http\Controllers\ReportController::class, 'loans'])->name('loans');
        Route::get('/installments', [\App\Http\Controllers\ReportController::class, 'installments'])->name('installments');
        Route::get('/financial', [\App\Http\Controllers\ReportController::class, 'financial'])->name('financial');
    });
    
    Route::resource('users', \App\Http\Controllers\UserController::class)->middleware('role:admin');
});

// require __DIR__.'/auth.php';
